#Global settings
globals:
  #Skill gains, these are exponential based on current skill so dont stray to far
  skillgainrate:
    unarmed: 1.0
    sword: 1.0
    archery: 1.0
    pickaxe: 1.0
    axe: 1.0
    shovel: 1.0
    hoe: 1.0
    heavyarmor: 1.0
    lightarmor: 1.0
    mining: 1.0
    woodcutting: 1.0
    digging: 1.0
    farming: 1.0
#Settings for a starting character    
defaultplayer:
  strength: 100.0
  dexterity: 100.0
  stamina: 100.0
  intelligence: 100.0
  wisdom: 100.0
  unarmeddamage: 0.5
  skills:
    unarmed: 50.0
    sword: 0.0
    archery: 0.0
    pickaxe: 0.0
    axe: 0.0
    shovel: 0.0
    hoe: 0.0
    heavyarmor: 0.0
    lightarmor: 0.0
    mining: 0.0
    woodcutting: 0.0
    digging: 0.0
    farming: 0.0
      
mobs:
  bat:
    name: Bat
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    #loot tables need an itemname with a chance, if you want multiple of one item to have a chance, then put more that one in the list
    loot:
      itemnames: [ practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 0.1, 0.1, 0.1, 0.1, 0.1 ]
    
  blaze:
    name: Blaze
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 0.1, 0.1, 0.1, 0.1, 0.1 ]
    
  cavespider:
    name: Cave Spider
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 0.1, 0.1, 0.1, 0.1, 0.1 ]
    
  chicken:
    name: Chicken
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ rawchicken, practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 1.0, 0.1, 0.1, 0.1, 0.1, 0.1 ]
    
  cow:
    name: Cow
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ rawbeef, practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 1.0, 0.1, 0.1, 0.1, 0.1, 0.1 ]
  
  creeper:
    name: Creeper
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 0.1, 0.1, 0.1, 0.1, 0.1 ]
  
  enderman:
    name: Enderman
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 0.1, 0.1, 0.1, 0.1, 0.1 ]
  
  enderdragon:
    name: Ender Dragon
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 0.1, 0.1, 0.1, 0.1, 0.1 ]
  
  ghast:
    name: Ghast
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 0.1, 0.1, 0.1, 0.1, 0.1 ]
  
  irongolem:
    name: Iron Golem
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 0.1, 0.1, 0.1, 0.1, 0.1 ]
  
  magamacube:
    name: Magma Cube
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 0.1, 0.1, 0.1, 0.1, 0.1 ]
  
  mushroomcow:
    name: Mushroom Cow
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 0.1, 0.1, 0.1, 0.1, 0.1 ]
  
  ocelot:
    name: Ocelot
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 0.1, 0.1, 0.1, 0.1, 0.1 ]
  
  pig:
    name: Pig
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ rawporkchop, practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 1.0, 0.1, 0.1, 0.1, 0.1, 0.1 ]
  
  pigzombie:
    name: Pig Zombie
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ rottenflesh, practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 0.5, 0.1, 0.1, 0.1, 0.1, 0.1 ]
  
  sheep:
    name: Sheep
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 0.1, 0.1, 0.1, 0.1, 0.1 ]
  
  silverfish:
    name: Silverfish
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 0.1, 0.1, 0.1, 0.1, 0.1 ]
  
  skeleton:
    name: Skeleton
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 0.1, 0.1, 0.1, 0.1, 0.1 ]
  
  slime:
    name: Slime
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 0.1, 0.1, 0.1, 0.1, 0.1 ]
  
  snowman:
    name: Snowman
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 0.1, 0.1, 0.1, 0.1, 0.1 ]
  
  spider:
    name: Spider
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 0.1, 0.1, 0.1, 0.1, 0.1 ]
  
  squid:
    name: Squid
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ rawfish, practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 1.0, 0.1, 0.1, 0.1, 0.1, 0.1 ]
  
  villager:
    name: Villager
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 0.1, 0.1, 0.1, 0.1, 0.1 ]
  
  witch:
    name: Witch
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 0.1, 0.1, 0.1, 0.1, 0.1 ]
  
  wither:
    name: Wither
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 0.1, 0.1, 0.1, 0.1, 0.1 ]
  
  wolf:
    name: Wolf
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 0.1, 0.1, 0.1, 0.1, 0.1 ]
  
  zombie:
    name: Zombie
    strength: 10.0
    dexterity: 10.0
    stamina: 10.0
    intelligence: 10.0
    wisdom: 10.0
    experience: 1
    combatskill: unarmed
    damage: 1.0
    skills:
      unarmed: 50.0
      sword: 0.0
      archery: 0.0
      pickaxe: 0.0
      axe: 0.0
      shovel: 0.0
      hoe: 0.0
      heavyarmor: 0.0
      lightarmor: 0.0
      mining: 0.0
      woodcutting: 0
      digging: 0.0
      farming: 0.0
    loot:
      itemnames: [ rottenflesh, practicesword, practiceaxe, practicepick, practicehoe, practiceshovel ]
      itemchances: [ 1.0, 0.1, 0.1, 0.1, 0.1, 0.1 ]

items:
  #Food
  apple:
    name: Apple
    look: apple
    
  bakedpotato:
    name: Baked Potato
    look: bakedpotato
    
  bread:
    name: Bread
    look: bread
    
  cake:
    name: Cake
    look: cake
    
  carrot:
    name: Carrot
    look: carrot
    
  cookedchicken:
    name: Cooked Chicken
    look: cookedchicken
    
  cookedfish:
    name: Cooked Fish
    look: cookedfish
    
  cookedporkchop:
    name: Cooked Porkchop
    look: cookedpork
    
  cookie:
    name: Cookie
    look: cookie
    
  goldenapple:
    name: Golden Apple
    look: goldenapple
    
  goldencarrot:
    name: Golden Carrot
    look: goldencarrot
    
  melonslice:
    name: Melon Slice
    look: melonslice
    
  mushroomstew:
    name: Mushroom Stew
    look: mushroomstew
    
  poisonouspotato:
    name: Poisonous Potato
    look: poisonouspotato
    
  potato:
    name: Potato
    look: potato
    
  pumpkinpie:
    name: Pumpkin Pie
    look: pumpkinpie
    
  rawbeef:
    name: Raw Beef
    look: rawbeef
    
  rawchicken:
    name: Raw Chicken
    look: rawchicken
    
  rawfish:
    name: Raw Fish
    look: rawfish
    
  rawporkchop:
    name: Raw Porkchop
    look: rawporkchop
    
  rottenflesh:
    name: Rotten Flesh
    look: rottenflesh
    
  spidereye:
    name: Spider Eye
    look: spidereye
    
  steak:
    name: Steak
    look: steak
  
  #Some Practice weapons first
  practicesword:
    name: Practice Sword
    look: woodensword
    damage: 2.0
    value: 2.0
    
  practiceaxe:
    name: Practice Axe
    look: woodenaxe
    damage: 2.0
    value: 2.0
    
  practicepick:
    name: Practice Pickaxe
    look: woodenpickaxe
    damage: 2.0
    value: 2.0
    
  practicehoe:
    name: Practice Hoe
    look: woodenhoe
    damage: 2.0
    value: 2.0
    
  practiceshovel: 
    name: Practice Shovel
    look: woodenshovel
    damage: 2.0
    value: 2.0
  
  #Splintered Weapons
  splinteredsword:
    name: Splintered Sword
    look: woodensword
    damage: 3.0
    value: 5.0
    
  splinteredaxe:
    name: Splintered Axe
    look: woodenaxe
    damage: 3.0
    value: 5.0
    
  splinteredpick:
    name: Splintered Pickaxe
    look: woodenpick
    damage: 3.0
    value: 5.0
    
  splinteredhoe:
    name: Splintered How
    look: woodenhoe
    damage: 3.0
    value: 5.0
    
  splinteredshovel:
    name: Splintered Shovel
    look: woodenshovel
    damage: 3.0
    value: 5.0
    