name: Mine Fall RPG
main: com.totaldowner.minefall.MineFallRPG
version: ${version}
description: Plugin to create a RPG/MMO environment with skills and stats instead of experience/levels
database: false

commands:
  minefall:
    description: Various commands for MFRPG
    permission: minefallrpg.minefall
    permission-message: None shall pass
    usage: /minefall [command], try /minefall help for more options
  mf:
    description: Various commands for MFRPG
    permission: minefallrpg.minefall
    permission-message: None shall pass
    usage: /minefall [command], try /mf help for more options
  mfdebug:
    description: Various debugging commands for MFRPG
    permission: minefallrpg.debug
    permission-message: None shall pass
    usage: /mfdebug [command], try /mfdebug help for more options
  mfop:
    description: Various op commands for MFRPG
    permission: minefallrpg.op
    permission-message: None shall pass
    usage: /mfop [command], try /mfop help for more options
    
permissions:
  minefallrpg.debug:
    description: Access to various mfrpg debugging commands
    default: op
  minefallrpg.minefall:
    description: Access to various mfrpg player commands
    default: true
  minefallrpg.op:
    description: Access to mfrpg op commands
    deaulft: op